// Command Shortener 1.0.1 — paste this entire file into Cloudflare Workers.
const enc = new TextEncoder();
const SCHEMA = [
`CREATE TABLE IF NOT EXISTS admin (id INTEGER PRIMARY KEY CHECK(id=1), username TEXT NOT NULL, salt TEXT NOT NULL, hash TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS commands (slug TEXT PRIMARY KEY, name TEXT NOT NULL, content TEXT NOT NULL, mode TEXT NOT NULL, shell TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', enabled INTEGER NOT NULL DEFAULT 1, created TEXT NOT NULL, updated TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS attempts (ip TEXT PRIMARY KEY, count INTEGER NOT NULL, start INTEGER NOT NULL)`];
let ready;
async function init(env) {
 if (!ready) ready = (async()=>{for(const s of SCHEMA) await env.DB.prepare(s).run(); if(!await env.DB.prepare('SELECT id FROM admin WHERE id=1').first()) { const salt=crypto.randomUUID(); const hash=await password(env.ADMIN_PASSWORD,salt); await env.DB.prepare('INSERT OR IGNORE INTO admin(id,username,salt,hash) VALUES(1,?,?,?)').bind(env.ADMIN_USER,salt,hash).run(); }})();
 try {await ready;} catch(e){ready=undefined;throw e;}
}
async function password(p,s) {const k=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveBits']); return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(s),iterations:100000,hash:'SHA-256'},k,256));}
function hex(b){return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function equal(a,b){let x=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)x|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return x===0;}
async function sign(s,key){const k=await crypto.subtle.importKey('raw',enc.encode(key),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',k,enc.encode(s)));}
async function session(req,env,a){const m=(req.headers.get('Cookie')||'').match(/(?:^|;\s*)session=([^;]+)/);if(!m)return false; const parts=m[1].split('.');if(parts.length!==4)return false;const [exp,v,n,sig]=parts;return Number(exp)>Date.now()&&Number(exp)<Date.now()+86400001&&Number(v)===a.version&&equal(sig,await sign([exp,v,n].join('.'),env.SESSION_SECRET));}
function response(body,status=200,type='application/json; charset=utf-8',extra={}){return new Response(type.startsWith('application/json')?JSON.stringify(body):body,{status,headers:{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer',...extra}});}
function fail(msg,status=400){return response({error:msg},status);}
async function body(req){const text=await req.text();if(enc.encode(text).length>2500000)throw Error('请求过大');return JSON.parse(text);}
function validate(x){const slug=String(x.slug||'').trim();if(!/^[a-zA-Z0-9_-]+(?:\/[a-zA-Z0-9_-]+)*$/.test(slug)||slug.length>100||['admin','api','favicon.ico'].includes(slug.split('/')[0]))throw Error('短路径仅支持英文、数字、下划线、横线和分层斜线；admin/api 为保留路径');const name=String(x.name||'').trim(),content=String(x.content||'').replace(/\r\n?/g,'\n');if(!name||name.length>100||!content.trim()||enc.encode(content).length>200000)throw Error('名称不能为空且不超过100字；命令或脚本不能为空且不超过200KB');if(!['command','snapshot'].includes(x.mode)||!['bash','sh'].includes(x.shell))throw Error('模式或执行器不正确');const note=String(x.note||'');if(note.length>1000)throw Error('备注过长');return {slug,name,content,mode:x.mode,shell:x.shell,note,enabled:x.enabled===false||x.enabled===0?0:1};}
function script(c){return c.mode==='snapshot'?c.content.replace(/^#![^\n]*\n?/,'')+'\n':'# Saved command; executed on the requesting machine.\n'+c.content+'\n';}
export default {async fetch(req,env){try {
 const url=new URL(req.url),p=url.pathname;
 if(p==='/'||p==='/admin'||p==='/admin/')return response(HTML,200,'text/html; charset=utf-8',{'Content-Security-Policy':"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'; form-action 'self'"});
 if(!env.DB||!env.ADMIN_USER||!env.ADMIN_PASSWORD||!env.SESSION_SECRET||env.ADMIN_PASSWORD.length<12||env.SESSION_SECRET.length<32)return p.startsWith('/api/')?fail('请绑定 DB，并设置 ADMIN_USER、至少12位 ADMIN_PASSWORD、至少32位 SESSION_SECRET',503):response('配置未完成\n',503,'text/plain; charset=utf-8');
 if(p.startsWith('/api/')) {
 await init(env);const a=await env.DB.prepare('SELECT * FROM admin WHERE id=1').first();
 if(req.method!=='GET'&&req.headers.get('Origin')!==url.origin)return fail('请求来源无效',403);
 if(p==='/api/login'&&req.method==='POST') {
 const ip=req.headers.get('CF-Connecting-IP')||'local',now=Date.now();await env.DB.prepare('DELETE FROM attempts WHERE start < ?').bind(now-900000).run();
 const at=await env.DB.prepare('SELECT * FROM attempts WHERE ip=?').bind(ip).first();if(at&&at.count>=10)return fail('尝试次数过多，请15分钟后重试',429);
 await env.DB.prepare('INSERT INTO attempts(ip,count,start) VALUES(?,1,?) ON CONFLICT(ip) DO UPDATE SET count=count+1').bind(ip,now).run();
 const b=await body(req);if(typeof b.password!=='string'||b.password.length>512||b.username!==a.username||!equal(await password(b.password,a.salt),a.hash))return fail('账号或密码错误',401);
 await env.DB.prepare('DELETE FROM attempts WHERE ip=?').bind(ip).run();const token=[now+86400000,a.version,crypto.randomUUID()].join('.');return response({ok:true},200,undefined,{'Set-Cookie':'session='+token+'.'+await sign(token,env.SESSION_SECRET)+'; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=86400'});
 }
 if(!await session(req,env,a))return fail('请先登录',401);
 if(p==='/api/logout'&&req.method==='POST'){await env.DB.prepare('UPDATE admin SET version=version+1 WHERE id=1').run();return response({ok:true},200,undefined,{'Set-Cookie':'session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});}
 if(p==='/api/me'&&req.method==='GET')return response({username:a.username});
 if(p==='/api/account'&&req.method==='POST'){const b=await body(req);if(typeof b.current!=='string'||b.current.length>512||!equal(await password(b.current,a.salt),a.hash))return fail('当前密码错误');if(typeof b.password!=='string'||b.password.length<12||b.password.length>512||typeof b.username!=='string'||!b.username.trim()||b.username.length>100)return fail('账号不能为空，密码需要12至512位');const salt=crypto.randomUUID();await env.DB.prepare('UPDATE admin SET username=?,salt=?,hash=?,version=version+1 WHERE id=1').bind(b.username.trim(),salt,await password(b.password,salt)).run();return response({ok:true});}
 if(p==='/api/commands'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM commands ORDER BY updated DESC').all();return response({commands:r.results});}
 if(p==='/api/commands'&&req.method==='POST'){const b=await body(req),c=validate(b),now=new Date().toISOString();if(b.original){const old=await env.DB.prepare('SELECT slug FROM commands WHERE slug=?').bind(b.original).first();if(!old)return fail('记录已不存在',404);try{await env.DB.prepare('UPDATE commands SET slug=?,name=?,content=?,mode=?,shell=?,note=?,enabled=?,updated=? WHERE slug=?').bind(c.slug,c.name,c.content,c.mode,c.shell,c.note,c.enabled,now,b.original).run();}catch(e){if(String(e).includes('UNIQUE'))return fail('短路径已存在',409);throw e;}}else{try{await env.DB.prepare('INSERT INTO commands VALUES(?,?,?,?,?,?,?,?,?)').bind(c.slug,c.name,c.content,c.mode,c.shell,c.note,c.enabled,now,now).run();}catch(e){if(String(e).includes('UNIQUE'))return fail('短路径已存在',409);throw e;}}const saved=await env.DB.prepare('SELECT * FROM commands WHERE slug=?').bind(c.slug).first();return response({ok:true,command:saved});}
 if(p==='/api/commands'&&req.method==='DELETE'){const b=await body(req);await env.DB.prepare('DELETE FROM commands WHERE slug=?').bind(String(b.slug)).run();return response({ok:true});}
 if(p==='/api/import'&&req.method==='POST'){const b=await body(req);if(b.version!==1||!Array.isArray(b.commands)||b.commands.length>1000)return fail('备份格式错误，单次最多1000条');const rows=b.commands.map(validate),seen=new Set();for(const c of rows){if(seen.has(c.slug))return fail('备份内路径重复');seen.add(c.slug);}const now=new Date().toISOString();try{if(rows.length)await env.DB.batch(rows.map(c=>env.DB.prepare('INSERT INTO commands VALUES(?,?,?,?,?,?,?,?,?)').bind(c.slug,c.name,c.content,c.mode,c.shell,c.note,c.enabled,now,now)));}catch(e){if(String(e).includes('UNIQUE'))return fail('有路径与现有记录重复，本次导入已撤销；请修改备份中的路径',409);throw e;}return response({ok:true,count:rows.length});}
 return fail('接口不存在',404);
 }
 if(req.method!=='GET'&&req.method!=='HEAD')return response('Method not allowed\n',405,'text/plain; charset=utf-8');
 let slug;try{slug=decodeURIComponent(p.slice(1));}catch{return response('Invalid path\n',400,'text/plain; charset=utf-8');}
 // Public reads never create tables or write usage counters.
 let c;try{c=await env.DB.prepare('SELECT * FROM commands WHERE slug=? AND enabled=1').bind(slug).first();}catch(e){if(String(e).includes('no such table'))return response('请先登录后台完成初始化\n',503,'text/plain; charset=utf-8');throw e;}
 if(!c)return response('Not found\n',404,'text/plain; charset=utf-8');return response(req.method==='HEAD'?null:script(c),200,'text/plain; charset=utf-8');
 }catch(e){console.error(e);return fail(e instanceof SyntaxError?'JSON 格式错误':/请求过大|短路径|名称不能为空|模式或执行器|备注过长/.test(e.message)?e.message:'服务异常，请查看 Worker 日志',400);}}};
const HTML = String.raw`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>短命令 · 命令管理</title><style>
:root{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#182a36;background:#f4f7fa}*{box-sizing:border-box}body{margin:0}header{background:#102a38;color:white;padding:24px max(20px,calc((100vw - 1120px)/2));display:flex;align-items:center;justify-content:space-between}header b{font-size:25px}header small{display:block;color:#adc3ce;margin-top:5px}main{max-width:1120px;margin:28px auto;padding:0 18px}.card{background:white;border:1px solid #dce5eb;border-radius:14px;padding:24px;margin-bottom:18px}.login{max-width:430px;margin:65px auto}h2{margin:0 0 18px;font-size:20px}label{display:block;font-size:14px;margin:15px 0 6px}input,textarea,select{font:inherit;width:100%;padding:11px 12px;border:1px solid #c8d5df;border-radius:8px;background:white}textarea{font-family:ui-monospace,monospace;resize:vertical}button{font:inherit;border:0;background:#087e8b;color:white;border-radius:8px;padding:10px 15px;cursor:pointer}button.secondary{background:#e9eff3;color:#244252}button.danger{background:#fff0ef;color:#ad3327}button:disabled{opacity:.5;cursor:wait}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.row>*{flex:1}.row button{flex:initial}.muted{color:#637987;font-size:13px;line-height:1.7}#notice{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#102a38;color:white;padding:12px 20px;border-radius:9px;max-width:90%;z-index:10}code,pre{font-family:ui-monospace,monospace}pre{background:#eef4f7;padding:14px;border-radius:8px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}.item{border-top:1px solid #e0e8ed;padding:20px 0}.item:first-child{border:0}.badge{font-size:12px;color:#087e8b;background:#e7f6f4;padding:4px 8px;border-radius:6px;margin-left:8px}.off{color:#916029;background:#fff1df}.title{display:flex;align-items:center;flex-wrap:wrap;gap:5px}.title b{font-size:17px}dialog{border:1px solid #d4e0e8;border-radius:14px;width:min(720px,95vw);max-height:92vh;padding:24px}dialog::backdrop{background:#102a3880}.hidden{display:none!important}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:20px}.toolbar input{flex:1;min-width:150px}.toolbar button{white-space:nowrap}.two{display:grid;grid-template-columns:1fr 1fr;gap:15px}summary{cursor:pointer;font-size:13px;color:#56717e}@media(max-width:600px){header{padding:20px}.card{padding:17px}.two{grid-template-columns:1fr}.toolbar button{flex:1}main{margin-top:18px}}
</style><header><div><b>短命令</b><small>把长命令，留在一个好记的地址里。</small></div><button id="logout" class="secondary hidden">退出登录</button></header><main>
<section id="login" class="card login"><h2>管理员登录</h2><p class="muted">登录后管理命令；短地址可直接从终端访问。</p><form id="loginform"><label>账号</label><input id="user" autocomplete="username" required><label>密码</label><input id="pass" type="password" autocomplete="current-password" required><button style="width:100%;margin-top:22px">登录</button></form></section>
<section id="app" class="hidden"><div class="toolbar"><input id="search" placeholder="搜索名称、路径或备注"><button id="add">＋ 添加命令</button><button id="export" class="secondary">导出备份</button><button id="import" class="secondary">导入备份</button><button id="account" class="secondary">账号设置</button><input id="file" class="hidden" type="file" accept=".json"></div><div class="card"><div class="row"><h2 style="flex:1;margin:0">我的命令 <span id="count" class="muted"></span></h2><span class="muted">默认永久保存</span></div><p class="muted">每个路径对应一条命令。编辑内容不会改变地址；修改路径会使旧地址失效。</p><div id="list"></div></div></section>
</main><dialog id="editor"><form id="editform"><h2 id="editTitle">添加命令</h2><div class="two"><div><label>名称</label><input id="name" required maxlength="100" placeholder="例如：Docker 安装"></div><div><label>短路径 / 独立前缀</label><input id="slug" required maxlength="100" placeholder="docker 或 tools/docker"></div></div><div class="two"><div><label>内容模式</label><select id="mode"><option value="command">原始命令 · 跟随源站</option><option value="snapshot">固定副本 · 粘贴完整脚本</option></select></div><div><label>执行器</label><select id="shell"><option value="bash">bash</option><option value="sh">sh</option></select></div></div><label id="contentlabel">原始一键命令</label><textarea id="content" rows="9" required placeholder="粘贴完整安装命令，支持多行"></textarea><p class="muted" id="modehelp"></p><label>备注</label><input id="note" maxlength="1000" placeholder="选填"><label><input id="enabled" type="checkbox" checked style="width:auto"> 启用短地址</label><label>生成的短命令</label><pre id="preview"></pre><div class="row"><button type="button" id="cancel" class="secondary">取消</button><button id="save">保存</button></div></form></dialog>
<dialog id="accountdialog"><form id="accountform"><h2>账号设置</h2><label>管理员账号</label><input id="newuser" required autocomplete="username"><label>当前密码</label><input id="currentpass" type="password" required autocomplete="current-password"><label>新密码（至少12位）</label><input id="newpass" type="password" required minlength="12" autocomplete="new-password"><label>确认新密码</label><input id="confirmpass" type="password" required minlength="12" autocomplete="new-password"><p class="muted">保存后全部登录会话失效。Cloudflare 中的初始密码不会覆盖已保存的新密码。</p><div class="row"><button id="cancelaccount" class="secondary" type="button">取消</button><button>保存并重新登录</button></div></form></dialog><div id="notice" class="hidden" role="status"></div>
<script>
const $=id=>document.getElementById(id);let records=[],original=null,timer,listRevision=0,loadSequence=0;
function toast(s){$('notice').textContent=s;$('notice').classList.remove('hidden');clearTimeout(timer);timer=setTimeout(()=>$('notice').classList.add('hidden'),5000)}
async function api(path,method='GET',data){const r=await fetch('/api/'+path,{method,cache:'no-store',headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const b=await r.json();if(!r.ok){if(r.status===401)show(false);throw Error(b.error||'请求失败')}return b}
function show(on){$('login').classList.toggle('hidden',on);$('app').classList.toggle('hidden',!on);$('logout').classList.toggle('hidden',!on)}
function link(c){return location.origin+'/'+c.slug}
function command(c){return c.shell+' <(curl -fsSL '+link(c)+')'}
function portable(c){return 'curl -fsSL '+link(c)+' | '+c.shell}
async function copy(s){try{await navigator.clipboard.writeText(s);toast('已复制')}catch{toast('自动复制失败，请从命令框手动复制')}}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function action(label,fn,cls){const b=el('button',label,cls);b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){toast(e.message)}finally{b.disabled=false}};return b}
async function load(){const seq=++loadSequence,rev=listRevision;const data=await api('commands');if(seq!==loadSequence||rev!==listRevision)return;records=data.commands;render()}
function render(){const q=$('search').value.toLowerCase();$('count').textContent=records.length+' 条';$('list').replaceChildren();const list=records.filter(c=>(c.name+' '+c.slug+' '+c.note).toLowerCase().includes(q));if(!list.length)$('list').append(el('p',records.length?'没有匹配的命令。':'还没有命令，点击“添加命令”开始。','muted'));for(const c of list){const item=el('div',undefined,'item'),title=el('div',undefined,'title');title.append(el('b',c.name),el('span',c.enabled?'已启用':'已禁用','badge'+(c.enabled?'':' off')),el('span',c.mode==='snapshot'?'固定副本':'跟随源站','badge'));item.append(title,el('p','/'+c.slug+(c.note?' · '+c.note:''),'muted'));item.append(el('pre',command(c)));const buttons=el('div',undefined,'row');buttons.append(action('复制短命令',()=>copy(command(c))),action('复制管道格式',()=>copy(portable(c)),'secondary'),action('编辑',()=>edit(c),'secondary'),action(c.enabled?'禁用':'启用',async()=>{await api('commands','POST',{...c,original:c.slug,enabled:!c.enabled});await load()},'secondary'),action('删除',async()=>{if(confirm('删除 '+c.name+'？短地址将立即失效。')){await api('commands','DELETE',{slug:c.slug});await load()}},'danger'));item.append(buttons);const details=el('details'),summary=el('summary','查看保存内容');details.append(summary,el('pre',c.content),el('p','更新时间：'+new Date(c.updated).toLocaleString(),'muted'));item.append(details);$('list').append(item)}}
function preview(){const c={slug:$('slug').value.trim()||'你的路径',shell:$('shell').value};$('preview').textContent=command(c)+'\n\n'+portable(c);const fixed=$('mode').value==='snapshot';$('contentlabel').textContent=fixed?'完整脚本内容':'原始一键命令';$('modehelp').textContent=fixed?'请粘贴你确认过的完整脚本。此副本不会自动更新；内部下载依赖仍可能受源站影响。':'原始命令将保存为脚本，在调用者的终端执行。平台不会执行或自动改写你的命令。';}
function edit(c){original=c?c.slug:null;$('editTitle').textContent=c?'编辑命令':'添加命令';for(const id of ['name','slug','content','note'])$(id).value=c?c[id]:'';$('mode').value=c?c.mode:'command';$('shell').value=c?c.shell:'bash';$('enabled').checked=c?!!c.enabled:true;preview();$('editor').showModal()}
$('loginform').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await api('login','POST',{username:$('user').value,password:$('pass').value});$('pass').value='';show(true);await load()}catch(e){toast(e.message)}finally{b.disabled=false}};
$('editform').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{const result=await api('commands','POST',{original,name:$('name').value,slug:$('slug').value,content:$('content').value,note:$('note').value,mode:$('mode').value,shell:$('shell').value,enabled:$('enabled').checked});if(!result.command)throw Error('保存响应异常，请刷新页面确认记录');listRevision++;records=records.filter(c=>c.slug!==original&&c.slug!==result.command.slug);records.unshift(result.command);$('search').value='';render();$('editor').close();toast('已保存，命令已显示在列表中')}catch(e){toast(e.message)}finally{$('save').disabled=false}};
$('logout').onclick=async()=>{try{await api('logout','POST',{});records=[];show(false)}catch(e){toast(e.message)}};
$('add').onclick=()=>edit(null);$('cancel').onclick=()=>$('editor').close();$('search').oninput=render;for(const id of ['slug','shell','mode'])$(id).addEventListener('input',preview);
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exported:new Date().toISOString(),commands:records},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=el('a');a.href=u;a.download='short-commands-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>2500000)throw Error('备份超过2.5MB，请拆分导入');const data=JSON.parse(await f.text());if(confirm('导入备份？仅添加新路径；如有路径冲突，整批撤销。')){const r=await api('import','POST',data);await load();toast('已导入 '+r.count+' 条')}}catch(e){toast(e.message)}finally{$('file').value=''}};
$('account').onclick=async()=>{try{const a=await api('me');$('accountform').reset();$('newuser').value=a.username;$('accountdialog').showModal()}catch(e){toast(e.message)}};$('cancelaccount').onclick=()=>$('accountdialog').close();
$('accountform').onsubmit=async e=>{e.preventDefault();if($('newpass').value!==$('confirmpass').value)return toast('两次新密码不一致');e.submitter.disabled=true;try{await api('account','POST',{username:$('newuser').value,current:$('currentpass').value,password:$('newpass').value});$('accountdialog').close();show(false);toast('账号已更新，请重新登录')}catch(err){toast(err.message)}finally{e.submitter.disabled=false}};
(async()=>{try{await api('me');show(true);await load()}catch(e){if(e.message!=='请先登录')toast(e.message)}})();
</script></html>`;
